### ISSUE TITLE
Pass the conformance test tools 

### ISSUE THREAD

**Issue by herrjemand** [MasterKale/SimpleWebAuthn#14]
You guys should do this and become "compliant"! https://fidoalliance.org/certification/functional-certification/conformance/

**Comment by MasterKale** [comment]
I've just applied for access to the Test Tool. Time to head even deeper down the rabbit hole!

**Comment by MasterKale** [comment]
The Conformance Tools app is a hot Electron mess.

It turns out there's a WebAuthn-specific test suite, but it's only visible if you escape the Electron app and view the page from a browser. And of course the text box to specify a URL to run the tests against only appears in the app, which doesn't show the WebAuthn tests 🙀 

I logged an issue here to try and get some clarity on how to get past this: https://github.com/fido-alliance/conformance-tools-issues/issues/563

**Comment by MasterKale** [comment]
I'm happy to report that I've managed to get a conformance-specific test server up and running and have successfully run attestation tests against it:

<img width="267" alt="Screen Shot 2020-06-09 at 10 05 25 AM" src="https://user-images.githubusercontent.com/5166470/84178185-db28dc00-aa38-11ea-9e7b-4c8a9f09b0b1.png">

I'm working to get the codebase to pass these tests before I set my sights on passing assertion tests as well.

**Comment by MasterKale** [comment]
**It's official - SimpleWebAuthn now passes 100% of FIDO Conformance testing for FIDO2 Server Tests!** 🎉 🥳

<img width="600" alt="Screen Shot 2020-07-11 at 12 41 48 AM" src="https://user-images.githubusercontent.com/5166470/87266145-5f77e000-c479-11ea-9ced-8c878563be73.png">

This is now available in the newly-released v0.7.0 delivered in PR #25.
