### ISSUE TITLE
Validate timeout on the server

### ISSUE THREAD

**Issue by nflaig** [MasterKale/SimpleWebAuthn#224]
Hi @MasterKale,

I was wondering, is it important to validate the timeout on the server as well? Maybe there should be an expiration value which is stored together with the challenge itself. Such a check could be directly implemented in the `@simplewebauthn/server` library (`verifyRegistrationResponse` and `verifyAuthenticationResponse`) or alternatively could leave this responsibility up to the developer to do this themselves, in that case would probably make sense to update the example app.

**Comment by MasterKale** [comment]
> Generally, what I was wondering is if this is important or not in terms of security, maybe expiration would be some kind of indirect brute-force protection. In case it is a potential security improvement to have an expiration for the challenge on the service-side, maybe it makes sense to add this to the example app.

If you're trying to defend against brute force attempts, deleting a challenge once you retrieve it for verification could be another way to address this, in lieu of "use by" columns or auto-deleting values. One challenge, one attempt. 

The example server is half demo, half reference implementation (with plenty of hand-waving because there's no DB) and I confess it won't ever become something you'd run in production. I suppose there's room to hand-wave less about how the challenge gets remembered, but I don't think it's worth spending a ton of time on.

**Comment by nflaig** [comment]
> If you're trying to defend against brute force attempts, deleting a challenge once you retrieve it for verification could be another way to address this, in lieu of "use by" columns or auto-deleting values. One challenge, one attempt.

yeah true, that would probably better. But generally as I understand it, the challenge is mostly used to prevent replay attacks so I guess all those validations are really not that important.

Thanks for the explanations.
