### ISSUE TITLE
WebAuthn working in dev but not prod: Unexpected token e in JSON at position 0

### ISSUE THREAD

**Issue by arimendelow** [MasterKale/SimpleWebAuthn#294]
Hi! For some reason, WebAuthn isn’t working with my webapp once I deploy it. The most information I’m able to get is as follows:

```
Error while registering: Could not complete registration: Unexpected token e in JSON at position 0
    at Object.register
```

The Auth payloads look exactly the same in dev and prod. This happens in both Chrome and Safari.

This is specifically happening using RedwoodJS, you can see more information in the discussion there: https://community.redwoodjs.com/t/webauthn-cryptically-not-working-in-production-but-works-perfectly-in-development/4206

**Comment by MasterKale** [comment]
All of the chatter around this issue has been captured in that RedwoodJS communite thread. So far it seems like it might be something either RedwoodJS-related, or related to the project using RedwoodJS.

I'll leave this open till a resolution is discovered, in case it turns out it _is_ an issue with SimpleWebAuthn.

**Comment by arimendelow** [comment]
Resolution has been discovered, not an issue with SimpleWebAuthn :) thank you @MasterKale for all of your help and support, and thanks for the great library!
