### ISSUE TITLE
Version 6.2.1 not setting transport (Server)

### ISSUE THREAD

**Issue by jberrydev** [MasterKale/SimpleWebAuthn#301]
I recently upgraded to 6.2.1 using the examples and documentation provided.  Everything works well except it seems that transports is never set.  Is there something I may be missing as it seemed the transports were set in the previous version.

**Comment by MasterKale** [comment]
Can you help me understand your testing environment? What OS version, browser version, and authenticator are you trying to use?

**Comment by jberrydev** [comment]
Hey sorry, was busy earlier.  
Windows 10
Edge Browser
Yubi Key

After Registration and Authentication everything looks good except transports array is always empty. Following basic guide here: https://simplewebauthn.dev/docs/packages/server/

**Comment by MasterKale** [comment]
I'll bet you're suffering from the decision in Chrome 105 (and Edge too now, since it's Chromium-based) to **only return transports when you request direct attestation:**

https://twitter.com/IAmKale/status/1562168422082813952

> Heads up [#WebAuthn](https://twitter.com/hashtag/WebAuthn) fans, Chrome 105 (Beta rn) on Windows will only return transports for security keys if you request "direct" attestation. You'll no longer get an array containing only the transport that was used, because it could prevent use of unlisted but valid transports.

**@simplewebauthn/browser** simply ferries back the result of calling [`AuthenticatorAttestationResponse.getTransports()`](https://www.w3.org/TR/webauthn-2/#dom-authenticatorattestationresponse-gettransports). If you're getting back empty transports it's because the authenticator returns empty transports. In this case, because you're using something Chromium-based on Windows, I'll bet the "fix" for this is to request direct attestation.

Otherwise, store the empty array and simply pass it back to Windows Hello on subsequent auths. Transports are supposed to be "opaque" values to RP's anyway, since they're intended to be [**browser hints**](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialdescriptor-transports) as opposed to anything you should build business logic on top of.

**Comment by jberrydev** [comment]
> I'll bet you're suffering from the decision in Chrome 105 (and Edge too now, since it's Chromium-based) to **only return transports when you request direct attestation:**
> 
> https://twitter.com/IAmKale/status/1562168422082813952
> 
> > Heads up [#WebAuthn](https://twitter.com/hashtag/WebAuthn) fans, Chrome 105 (Beta rn) on Windows will only return transports for security keys if you request "direct" attestation. You'll no longer get an array containing only the transport that was used, because it could prevent use of unlisted but valid transports.
> 
> **@simplewebauthn/browser** simply ferries back the result of calling [`AuthenticatorAttestationResponse.getTransports()`](https://www.w3.org/TR/webauthn-2/#dom-authenticatorattestationresponse-gettransports). If you're getting back empty transports it's because the authenticator returns empty transports. In this case, because you're using something Chromium-based on Windows, I'll bet the "fix" for this is to request direct attestation.
> 
> Otherwise, store the empty array and simply pass it back to Windows Hello on subsequent auths. Transports are supposed to be "opaque" values to RP's anyway, since they're intended to be [**browser hints**](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialdescriptor-transports) as opposed to anything you should build business logic on top of.

I will try this out!  Thank you for your quick response.  I should have noticed this.  I will update and test and close.

**Comment by MasterKale** [comment]
@jberrydev Were you able to confirm that this was the case? I'm curious to hear back because every observation like yours is a data point I can use to better track the development of this stuff.

**Comment by jberrydev** [comment]
@MasterKale hey sorry about late response. Setting the attestation to direct did not seem to help with the transports.  Is there something specific I need to call that might not be in the documentation?
