### ISSUE TITLE
Add option to convert all buffers to base64

### ISSUE THREAD

**Issue by zoellner** [MasterKale/SimpleWebAuthn#317]
Currently the server package still requires some manual back and forth conversion between buffer and base64 depending on what's used to store the authenticator data. It'd be great of the library could have an option to convert everything behind the scenes such that for a user of the library everything is a string. 

Not every database handles storing buffers well (e.g. DynamoDB)

Example: 

- after `verifyRegistrationResponse` the `verification.registrationInfo.credentialID` is a Buffer
but client side startAuthentication returns a base64 string for the credentialID - so the user has to match the conversion (url safe I assume) to perform the lookup

**Comment by MasterKale** [comment]
@zoellner Thank you for the suggestion. I've been trying to think of what an option might look like, but am still not sure if this is something I'd want to make part of this project. Trying to build an API for potential data storage is not something I've wanted to tackle, hence my "cop out" of simply returning raw bytes and going, "store it however you want, RP devs!"

There's an upcoming helper called `isoBase64URL` that will debut with v7.0.0 soon after the new year. I wonder, would being able to do something like this help a dev like you, only being able to store strings (for sake of example)?

```js
import { isoBase64URL } from '@simplewebauthn/server/helpers';

const verified = verifyRegistrationResponse({
  // ...
});

const strCredendtialID: string = isoBase64URL.fromBuffer(verified.registrationInfo.credentialID);
```

You could then use `toBuffer()` as well to go back to bytes for, say, `generateAuthenticationOptions()`.

I'm just throwing out this idea for feedback. It's currently what I'm leaning towards saying is the solution to this particular issue, but I'd love your feedback.

**Comment by zoellner** [comment]
I am currently doing the conversions as you described in the code snippet. Providing the from/to conversions to make sure we can use the same ones as are used internally certainly would help. 

I'd agree with that approach if it was consistent everywhere. But given the need to serialize anyways to go from browser to server and the one case I mentioned in the ticket where the presumably matching output and input aren't compatible without a manual conversion I still think that a switch to just always expect and return serialized versions would still make the job for the developer easier without losing generality.

**Comment by MasterKale** [comment]
> (url safe I assume)

To clarify this point, this project only uses base64url encoding for outputs because of [its explicit callout as a dependency in the WebAuthn spec](https://www.w3.org/TR/webauthn-2/#sctn-dependencies). 

> I'd agree with that approach if it was consistent everywhere.

Do you mean consistent within SimpleWebAuthn? Or when working with WebAuthn in general?

> ...where the presumably matching output and input aren't compatible without a manual conversion...

There's two possible situations here:

1. An RP takes `credentialID` after registration and stores it and `credentialPublicKey` as bytes in the database. On a subsequent authentication attempt they must **decode** `credential.id` within an authentication response to bytes to look up the credential in the DB before passing both `credentialID` and `credentialPublicKey` into `verifyAuthenticationResponse()` (as the `authenticator` argument).
2. An RP takes `credentialID` after registration and stores it and `credentialPublicKey` as base64url strings in the database. On subsequent authentication attempts they use `credential.id` coming into the handler as-is to look up the credential in the DB, but must then **decode** `credentialID` and `credentialPublicKey` anyway to pass into `verifyAuthenticationResponse()`.

This feels like a damned if you do, damned if you don't situation. No matter how I think about this there's going to be encoding/decoding involved, this discussion is focused on _when_ it occurs. I know I constantly yammer on that I strive to make WebAuthn "simple" to use, but in a case like this I think it might be simpler to continue consistently returning raw bytes and leave it to the RP to figure out a lookup and storage schema that works for them.

I wonder if the frustration here is more related to DynamoDB and its inability to store bytes-like values...

**Comment by MasterKale** [comment]
I'm going to close this out as I won't be taking any action on this for now.
