### ISSUE TITLE
Base64 encoding should not use padding

### ISSUE THREAD

**Issue by Southclaws** [MasterKale/SimpleWebAuthn#330]
I've noticed a bug when setting my `userHandle` value to `okoko` which causes the value to be encoded as `b2tva28=` - with padding. The spec mentions that padding should not be used for WebAuthn (https://w3c.github.io/webauthn/#base64url-encoding) "...with all trailing '=' characters omitted..."

When running this code:
```ts
    // GET request to a WebAuthn compliant server with `username` set to "okoko"
    const response = await webAuthnGetAssertion(username);

    const credential = await startAuthentication(response.publicKey);
    console.log(credential.response.userHandle);
```

The output is

```
b2tva28=
```

And when the server parses this, it throws an error.

For now, I've simply fixed this by stripping the padding on the client before calling the API:

https://github.com/Southclaws/storyden/blob/a448311c2ed4b8c99e82110004818f8f8b681888/web/src/screens/auth/AuthMethod/WebAuthn/useWebAuthn.ts#L50-L56

I've opened an issue on the corresponding server library to see if we can make it a bit more lenient when it comes to Base64 padding (https://github.com/go-webauthn/webauthn/issues/93)

**Comment by MasterKale** [comment]
@simplewebauthn/browser doesn't actually encode `userHandle` to anything. Within the SimpleWebAuthn project the `user.id` value is only encoded/decoded as UTF-8:

https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/browser/src/methods/startAuthentication.ts#L92-L95

I made this decision because it was a practical pain in the butt having to always decode from base64url back to UTF-8 to understand the actual user ID from `userHandle` after an authentication.

I'll bet what's happening here is that, during registration, your back end code is encoding `okoko` to base64 (not base64url) before setting it as `user.id`. Then, during authentication, you're getting that value back which the library you're using to verify the response is expecting to be base64.

**Comment by james-d-elliott** [comment]
I have on several occasions noticed that either javascript itself or axios/fetch automatically encodes an object with binary data in this way when sending it as JSON, as to which one of these it is I'm not sure.

**Comment by MasterKale** [comment]
> Matthew does @simplewebauthn/server handle this case elegantly or does it reject invalid padding as well? If the former, did you do this intentionally and would you mind explaining? I'm mostly curious as I am presented with a decision regardless. I can open another issue if this is too off topic.

I'd rather not start a conversation like this in an issue like this one. Can you please start this as a new discussion since you're asking about a design decision as opposed to reporting a problem with the library?

**Comment by Southclaws** [comment]
I can't find any base64 encoding on my back end code so this might be from go-webauthn. I'll dig around and see if I can figure out at which point the username gets turned into base64. Thanks!

**Comment by Southclaws** [comment]
Alright I'm not sure what happened between then and now but the code in my original post no longer outputs in base64. This causes the backend to fail to parse. So for now I've just done `credential.response.userHandle = undefined;` and will cross this bridge another day (if it's even necessary to).

version: "@simplewebauthn/browser": "^7.0.0"

Will close for now as it seems like either a problem on my backend code or go-webauthn.
