### ISSUE TITLE
importing from deno.land fails caused by missing dep "src/dom.ts"

### ISSUE THREAD

**Issue by ingoradatz** [MasterKale/SimpleWebAuthn#460]
## Describe the issue

When I try the vendor the deno package it fails with

```
error: Module not found "https://deno.land/x/simplewebauthn@v8.3.2/packages/typescript-types/src/dom.ts".
    at https://deno.land/x/simplewebauthn@v8.3.2/packages/typescript-types/src/index.ts:23:8`
```

## Reproduction Steps

1. Open terminal with **deno** already installed
2. enter the deno project folder
3. `$> deno vendor https://deno.land/x/simplewebauthn/deno/server.ts --no-config --force`

## Expected behavior

It should download the simplewebauthn package to the `vendor/deno.land/x` folder

## Additional context

The `packages/typescript-types/src/dom.ts` file is normally automatically generated when simplewebauthn is packaged for uploading to deno.land? Maybe a CI-Problem?

**Comment by MasterKale** [comment]
Huh, I suppose it's unsurprising that you're getting a "Module not found" error here because **dom.ts** doesn't actually exist:

![Screenshot 2023-10-23 at 10 12 21 PM](https://github.com/MasterKale/SimpleWebAuthn/assets/5166470/6d9e3b10-acbe-402b-82df-6ed3781fac9d)

https://deno.land/x/simplewebauthn@v8.3.2/packages/typescript-types/src?source

Back when I only published to NPM this file would get generated and bundled into the published package. I guess I need to start tracking this file and periodically keeping it up-to-date so that it's available in Deno...

I wonder how I got this far with thinking this would work. I'm admittedly new to Deno development myself so I must not have "properly" bootstrapped a Deno project to test that importing from deno.land would pull this in without issue.

Let me think on how best to address this. Maybe it will be as easy as tracking this file and occassionally updating it.

**Comment by MasterKale** [comment]
@ingoradatz This should be resolved with the release of v8.3.3:

```sh
$> deno vendor https://deno.land/x/simplewebauthn/deno/server.ts --no-config --force
Warning Implicitly using latest version (v8.3.3) for https://deno.land/x/simplewebauthn/deno/server.ts
Vendored 169 modules into vendor/ directory.

To use vendored modules, specify the `--import-map vendor/import_map.json` flag when invoking Deno subcommands or add an `"importMap": "<path_to_vendored_import_map>"` entry to a deno.json file.
```

**Comment by spendres** [comment]
@ingoradatz

There is a simple deno.deploy using kv example at passkeys.deno.dev. It uses oak sessions and an early 8.x version of simplewebauthn. It may give you a head start.

@MasterKale 

The issue with webcrypto on cloudflare needing a check on the global namespace to know which webcrypto to import was where we left off in August. It's good to see that being resolved with other PRs. But, I have not verified that the proposed PR would not break Deno and am too busy on other fronts at the moment to do so – so just a note.

Steve

**Comment by spendres** [comment]
sorry... repo: https://github.com/maximousblk/passkeys-demo
