### ISSUE TITLE
`allowCredentials` should be specified precisely

### ISSUE THREAD

**Issue by agektmr** [MasterKale/SimpleWebAuthn#57]
To specify `allowCredentials`, `generateAssertionOptions()` currently requires `allowedCredentialIDs` to be an array of base64 credential ids and `transports` is fixed to `['usb', 'ble', 'nfc', 'internal']`, but it should be flexible for developers to specify specific transports.

https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/server/src/assertion/generateAssertionOptions.ts

I suggest adding an ability to pass [`CredentialDescriptor`s](https://w3c.github.io/webauthn/#dictionary-credential-descriptor) to `allowedCredentialIDs` (or should be renamed to `allowCredentials` for consistency with the spec) instead of just base64 credential ids.

**Comment by MasterKale** [comment]
Yeah, you're right that there needs to be the ability to specify transports _per_ credential. Looking at the way `allowCredentials` is currently composed from `allowedCredentialIDs` and `suggestedTransports`, it's just not flexible enough an approach and actually complicates things - not simple at all.

In fact, I'll probably make this a breaking change because the current functionality is not actually all that useful given the nuances of `allowCredentials` 😱

**Comment by MasterKale** [comment]
@agektmr This should be fixed as of **@simplewebauthn/browser@0.10.0** and **@simplewebauthn/server@0.10.1**.

**Please note that this did indeed involve breaking changes!** [Take a look at the v0.10.0 release notes](https://github.com/MasterKale/SimpleWebAuthn/releases/tag/v0.10.0) for more info on how you'll need to update your implementations of `generateAttestationOptions()` and `generateAssertionOptions()`.

**Comment by agektmr** [comment]
Amazing! This looks perfect.
