### ISSUE TITLE
Regarding the inconsistency of padding = at the end of base64 userId

### ISSUE THREAD

**Issue by Veclea** [MasterKale/SimpleWebAuthn#640]
Hello . Thanks for writing this great library. This is much more streamlined than my original manual fido implementation. Now I have implemented the registration part in windows. But when I started to test the login, the login assertion userHandle returned by the browser had an "=" at the end, but the userId of the registration request generated by your verification library did not have "=" at the end. I use string equality to determine credentials. Now the string judgment is not equal. I would like to ask you if this is a mistake in my use case?

![image](https://github.com/user-attachments/assets/8bf31df1-e611-4234-8a19-1021b94fb9f2)
![image](https://github.com/user-attachments/assets/f1931c1a-372b-46a9-ab92-cc67305af6df)

**Comment by Veclea** [comment]
I have fixed it

**Comment by samepant** [comment]
@Veclea what was your fix? I am seeing this as well, that calls to `verifyRegistrationResponse` result in credential ids with the padding (`=`) stripped out.

**Comment by samepant** [comment]
for anyone searching for similar problems in the future, the root cause of these issues is SimpleWebAuthn uses `base64URL` encoding, which is good, but you do need to make sure your client is handling encoded values in that specific encoding (it's different from normal `base64` in that a couple characters are switched and padding [`=`] is stripped out)
