### ISSUE TITLE
generateRegistrationOptions typings don't allow attestationType: "indirect"

### ISSUE THREAD

**Issue by jviide** [MasterKale/SimpleWebAuthn#657]
## Describe the issue

Version 13.0.0's typings do not allow giving `attestationType: "indirect"` as an option for `generateRegistrationOptions`. This was encountered when upgrading from v10, which allowed the value `"indirect"`.

Reporting here in case this is was an unintentional change, as it was not documented in release notes.

## Expected behavior

I suggest either of two actions:

 1. Modifying the `generateRegistrationOptions` typings to accept `attestationType: AttestationConveyancePreference`.
 2. Adding a short mention to release notes signaling that this was an intentional (and potentially breaking) change.

### SimpleWebAuthn Libraries

```sh
$ pnpm -r list --depth=0 | grep @simplewebauthn
@simplewebauthn/server 13.0.0
@simplewebauthn/browser 13.0.0
```

## Additional context

The change appears to have been made in commit https://github.com/MasterKale/SimpleWebAuthn/pull/653/commits/7cb74464678810bf322135dbe5e784951b9bb99e as a part of the pull request https://github.com/MasterKale/SimpleWebAuthn/pull/653.

Thank you for this library 🙂

**Comment by MasterKale** [comment]
Hello @jviide, I apologize for making trouble for you by omitting `"indirect"`. I intentionally didn't add it because I still can't see the practical utility of indirect attestation, especially as it gives the browser the ability to swap out the AAGUID and attestation statement with "privacy-friendly and/or more easily verifiable version of the same data" ([source](https://www.w3.org/TR/webauthn-2/#sctn-createCredential)). I wondered if anyone was actually using it for all of the guidance to use `"none"` or `"direct"`.

Can I ask you about how you're benefitting from indirect attestation? How are you establishing trust in the responses you're getting with the amount of agency indirect attestation gives browsers?

In the meantime I'll add back in `"indirect"`.

**Comment by MasterKale** [comment]
Hello @jviide, I've gone ahead and added a breaking change to the release notes for the dropping of support for `attestationType: 'indirect'` as having slept on it for a few days I still think the benefits of `'indirect'` are not enough for most RP's to take on trying to decide between none/indirect/direct. If it changes later I'll add it back in.

https://github.com/MasterKale/SimpleWebAuthn/releases/tag/v13.0.0
