### ISSUE TITLE
@simplewebauthn/browser v0.10.0 make Edge stuck on Windows 10

### ISSUE THREAD

**Issue by mahnunchik** [MasterKale/SimpleWebAuthn#75]
`@simplewebauthn/browser` v0.10.0 make Edge stuck on Windows 10.

```js
const { startAttestation, startAssertion } = require('@simplewebauthn/browser');

// never reached 
```

Build env: commonjs + webpack

**Comment by mahnunchik** [comment]
Edge Bundled with Windows 10 doesn't have `TextEncoder` 🤦 

https://github.com/MasterKale/SimpleWebAuthn/blob/a457a4aaf930ded31ec9454e64ace95361c6477e/packages/browser/src/helpers/toUint8Array.ts#L1

Even latest `classic Edge`: Microsoft Edge 44.19041.423.0

**Comment by MasterKale** [comment]
Aha, of course legacy Edge doesn't support `TextEncoder` 🤦 

caniuse confirms: https://caniuse.com/?search=TextEncoder

<img width="348" alt="Screen Shot 2020-11-26 at 10 06 56 AM" src="https://user-images.githubusercontent.com/5166470/100381988-22972a80-2fcf-11eb-9aaf-16ac44ce472e.png">

I'm torn on how to address this. SimpleWebAuthn supports "modern browsers" which I could argue omits legacy Edge for the Chromium version MS switched to. I see a couple of paths forward:

1.  I update documentation on **browser's** browser support and link to a polyfill when legacy Edge support is desired
2. I include a polyfill in **browser**

I'm inclined to go with Option 1. Option 2 would be a waste since it'd only be needed for a single now-deprecated browser.

@mahnunchik would you be willing to identify an `npm` polyfill package that fixes the issue? [MDN also includes a spec-compliant polyfill](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder#Polyfill) I could link to to solve this with advice to "[search NPM for 'textencoder polyfill browser'](https://www.npmjs.com/search?q=textencoder%20polyfill%20browser)"

**Comment by mahnunchik** [comment]
Yep, option 2 is overhead for this issue. I think that mention in the readme is enough.

I've faced with the issue while testing on **fresh** installation of Windows 10 VM from MS: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

It is surprised me a lot that latest Windows 10 ships with too outdated Microsoft Edge 44.19041.423.0

**Comment by mahnunchik** [comment]
@MasterKale I'm going to skip support of Edge < 79 for my product.

But polyfill may be required for products which must work on bare Windows 10, maybe bank or school software.

**Comment by MasterKale** [comment]
I've created a new "Edge Browser" page on the homepage with information about this issue, including suggestions on how to work around it: https://simplewebauthn.dev/docs/advanced/edge-browser

@mahnunchik Think there's anything more I should add?

**Comment by mahnunchik** [comment]
I think it is definitely enough. Thank you!
