### ISSUE TITLE
devices not explained

### ISSUE THREAD

**Issue by jkassis** [MasterKale/SimpleWebAuthn#92]
the use of the devices parameter in the online docs at `https://simplewebauthn.dev/docs/packages/server` is not explained.

**Comment by jkassis** [comment]
actually. i *do* get this now. these are the stored credentials for the user. the term `devices` is a little confusing

**Comment by MasterKale** [comment]
Ah, I see the problem, I neglected to access `devices` off of `user` like I do in the assertion example. It _should_ be `user.devices`, which is returned by the example's pseudocode `getUserFromDB()`.

I'll go ahead and fix that, and tweak "devices" to "authenticators" because you're right, "devices" is a little too vague and not often used to describe the types of objects that are used within the context of WebAuthn :v:

**Comment by MasterKale** [comment]
Okay, docs have been updated. It turns out I'd written another pseudocode method `getUserAuthenticators()` that I never actually leveraged in the example:

<img width="695" alt="Screen Shot 2021-01-26 at 4 19 36 PM" src="https://user-images.githubusercontent.com/5166470/105924022-4d632680-5ff2-11eb-8b85-33aad57d29cf.png">
